base_model: /root/cproject_updated/Qwen2.5-7B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

plugins:
  - axolotl.integrations.liger.LigerPlugin

liger_rope: true
liger_rms_norm: true
liger_swiglu: true
liger_fused_linear_cross_entropy: false

load_in_8bit: false
load_in_4bit: false
strict: false

auto_resume_from_checkpoints: true

datasets:
  - path: json
    data_files: /cproject_updated/6k_train_single_axolotl.jsonl
    ds_type: json
    type: completion

shuffle_merged_datasets: true
dataset_prepared_path: /root/cproject_updated/prnew142jgfkdgjdfkjdk
val_set_size: 0.05
output_dir: /root/cproject_updated/conv_200k_7b-r6
sequence_len: 8192
sample_packing: true
eval_sample_packing: false

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 2
optimizer: paged_adamw_8bit
lr_scheduler: cosine

learning_rate: 1e-6
adam_beta1: 0.75
adam_beta2: 0.90
max_grad_norm: 0.2
train_on_inputs: false
group_by_length: false
bf16: auto

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true

logging_steps: 1
flash_attention: true
warmup_steps: 5
eval_steps: 0
saves_per_epoch: 1

deepspeed: /root/axolotl/deepspeed_configs/zero3_bf16.json

auto_resume_from_checkpoints: false
wandb_project: corruption_model_rm
wandb_entity:
wandb_watch:
wandb_name: rm-test-v1-misc
wandb_log_model: